//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public double Weight { get; set; }
        public int ConsultingDoctor { get; set; }
        public System.DateTime DOB { get; set; }
        public string Disease { get; set; }
        public string Contact { get; set; }
        public int RegistrationFee { get; set; }
        public System.DateTime LastVisit { get; set; }
        public byte StatusFlag { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
